import {
  ArrowLeft, Send, Sparkles, Loader2, Trash2,
  Mic, MicOff, Image, Volume2, VolumeX, Download, Clock
} from "lucide-react";
import { useEffect, useRef, useState, useCallback } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { jsPDF } from "jspdf";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;

// ─── Types ───────────────────────────────────────────────────────────────────
type MsgType = "text" | "image" | "pdf-gen";
type Msg = {
  role: "user" | "assistant";
  content: string;
  type?: MsgType;
  imageUrl?: string;
  pdfFile?: string; // filename for generated PDF
};

// ─── Intent detection ─────────────────────────────────────────────────────────
function isImageRequest(text: string) {
  return (
    /^\/image\s+/i.test(text.trim()) ||
    /\b(generate|create|make|draw|show|produce)\b.{0,25}\b(image|picture|photo|illustration|art|painting)\b/i.test(text)
  );
}
function extractImagePrompt(text: string) {
  return text
    .replace(/^\/image\s*/i, "")
    .replace(/\b(generate|create|make|draw|show|produce)\b.{0,10}\b(an?\s+)?(image|picture|photo|illustration|art|painting)\b(\s+of|\s+for|\s+showing)?\s*/i, "")
    .trim() || text.trim();
}
function isPdfRequest(text: string) {
  return /\b(make|create|generate|write|build|produce|export)\b.{0,35}\bpdf\b/i.test(text);
}
function extractPdfTopic(text: string) {
  const m =
    text.match(/(?:about|on|for|regarding|covering)\s+(.+?)(?:\s+(?:as\s+a\s+)?pdf|$)/i) ||
    text.match(/pdf\s+(?:about|on|for|regarding|covering)\s+(.+)/i);
  if (m?.[1]) return m[1].trim();
  return text.replace(/\b(make|create|generate|write|build|produce|export|a|an|the|pdf)\b/gi, "").trim() || "Document";
}

// ─── TTS helper ───────────────────────────────────────────────────────────────
let ttsVoice: SpeechSynthesisVoice | null = null;
function loadVoice() {
  const voices = window.speechSynthesis?.getVoices() ?? [];
  // Prefer Google English voices, then any English voice
  ttsVoice =
    voices.find((v) => v.name.includes("Google") && v.lang.startsWith("en")) ||
    voices.find((v) => v.lang === "en-US") ||
    voices.find((v) => v.lang.startsWith("en")) ||
    null;
}
if (window.speechSynthesis) {
  loadVoice();
  window.speechSynthesis.onvoiceschanged = loadVoice;
}

function speak(text: string) {
  if (!window.speechSynthesis) return;
  window.speechSynthesis.cancel();
  // Strip markdown chars
  const clean = text.replace(/[*_`#>~\[\]()]/g, "").slice(0, 500);
  if (!clean.trim()) return;
  const utt = new SpeechSynthesisUtterance(clean);
  utt.voice = ttsVoice;
  utt.rate = 1.05;
  utt.pitch = 1.0;
  utt.volume = 1.0;
  utt.lang = "en-US";
  window.speechSynthesis.speak(utt);
}

// ─── PDF builder ─────────────────────────────────────────────────────────────
function buildPdf(title: string, content: string): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const m = 20, mw = pw - m * 2;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(80, 40, 180);
  doc.text(title, m, 28, { maxWidth: mw });

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 160, 160);
  doc.text(`Generated by Lumina AI · ${new Date().toLocaleDateString("en-IN")}`, m, 37);

  doc.setDrawColor(190, 170, 255);
  doc.setLineWidth(0.4);
  doc.line(m, 41, pw - m, 41);

  doc.setFontSize(11);
  doc.setTextColor(25, 25, 25);
  const clean = content.replace(/##\s*/g, "").replace(/\*\*/g, "").replace(/\*/g, "");
  const lines = doc.splitTextToSize(clean, mw);
  let y = 50;
  for (const line of lines) {
    if (y + 6 > ph - 18) { doc.addPage(); y = 20; }
    doc.text(line, m, y);
    y += 6;
  }
  const total = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(170);
    doc.text(`Page ${i} of ${total}  ·  Lumina AI`, m, ph - 10);
  }
  return doc;
}

// ─── Component ───────────────────────────────────────────────────────────────
export const ChatScreen = () => {
  const { user, profile } = useAuth();

  const [messages, setMessages] = useState<Msg[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [imgLoading, setImgLoading] = useState(false);
  const [imgTimer, setImgTimer] = useState(0);
  const [ttsOn, setTtsOn] = useState(false);
  const [micState, setMicState] = useState<"idle" | "requesting" | "listening" | "error">("idle");
  const [micTranscript, setMicTranscript] = useState("");
  const [pdfDocs, setPdfDocs] = useState<Record<string, jsPDF>>({}); // msgIndex -> doc

  const scrollRef = useRef<HTMLDivElement>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const recRef = useRef<any>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // ── Welcome message ────────────────────────────────────────────────────────
  useEffect(() => {
    (async () => {
      if (!user) {
        setMessages([{
          role: "assistant",
          content: "👋 Hi! I'm **Lumina**, your AI tutor.\n\n• 💬 Ask any question\n• 🖼️ Say \"generate image of...\" or type /image\n• 📝 Say \"make a PDF about...\" and I'll create a downloadable document\n• 🎤 Tap the mic to speak\n• 🔊 Toggle the speaker to hear my responses",
          type: "text",
        }]);
        return;
      }
      const { data } = await supabase
        .from("chat_messages")
        .select("role, content")
        .eq("user_id", user.id)
        .order("created_at", { ascending: true })
        .limit(50);
      setMessages(
        data?.length
          ? (data as Msg[])
          : [{
              role: "assistant",
              content: `Hey ${profile?.display_name?.split(" ")[0] || "there"}! 👋 What would you like to learn today?`,
              type: "text",
            }]
      );
    })();
  }, [user?.id]);

  // Auto-scroll
  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, loading, imgLoading]);

  // Image timer
  useEffect(() => {
    if (imgLoading) {
      setImgTimer(0);
      timerRef.current = setInterval(() => setImgTimer((t) => t + 1), 1000);
    } else {
      if (timerRef.current) clearInterval(timerRef.current);
    }
    return () => { if (timerRef.current) clearInterval(timerRef.current); };
  }, [imgLoading]);

  const persist = (m: Msg) => {
    if (!user) return;
    supabase.from("chat_messages").insert({ user_id: user.id, role: m.role, content: m.content });
  };

  const clear = async () => {
    if (!user) return;
    await supabase.from("chat_messages").delete().eq("user_id", user.id);
    setMessages([{ role: "assistant", content: "Cleared! What's next? ✨", type: "text" }]);
    setPdfDocs({});
  };

  // ── Voice ─────────────────────────────────────────────────────────────────
  const SpeechRec =
    (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;

  const stopMic = useCallback(() => {
    try { recRef.current?.stop(); } catch (_) {}
    recRef.current = null;
    setMicState("idle");
    setMicTranscript("");
  }, []);

  const startMic = useCallback(() => {
    if (!SpeechRec) {
      toast.error("Voice input requires Chrome or Edge browser.");
      setMicState("error");
      setTimeout(() => setMicState("idle"), 2000);
      return;
    }

    setMicState("requesting");
    // Ask for mic permission explicitly for a better UX
    navigator.mediaDevices
      .getUserMedia({ audio: true })
      .then(() => {
        const rec = new SpeechRec();
        rec.continuous = false;
        rec.interimResults = true;
        rec.lang = "en-US";
        rec.maxAlternatives = 1;

        rec.onstart = () => setMicState("listening");

        rec.onresult = (e: any) => {
          let interim = "";
          let final = "";
          for (let i = e.resultIndex; i < e.results.length; i++) {
            const t = e.results[i][0].transcript;
            if (e.results[i].isFinal) final += t;
            else interim += t;
          }
          setMicTranscript(interim || final);
          if (final) {
            setInput(final.trim());
            setMicTranscript("");
          }
        };

        rec.onerror = (e: any) => {
          const code: string = e?.error ?? "";
          if (code === "not-allowed" || code === "permission-denied") {
            toast.error("Microphone access denied. Please allow mic access in your browser settings.");
          } else if (code === "no-speech") {
            toast.info("No speech detected. Try again.");
          } else if (code === "network") {
            toast.error("Voice recognition needs an internet connection.");
          } else if (code === "aborted") {
            // silently ignore user-initiated abort
          } else {
            toast.error(`Voice error: ${code || "unknown"}. Try again.`);
          }
          setMicState("idle");
          setMicTranscript("");
        };

        rec.onend = () => {
          setMicState("idle");
          setMicTranscript("");
        };

        rec.start();
        recRef.current = rec;
      })
      .catch((err: any) => {
        const msg: string = err?.message ?? "";
        if (msg.includes("denied") || msg.includes("Permission")) {
          toast.error("Mic access denied. Enable it in your browser → Site Settings → Microphone.");
        } else {
          toast.error(`Could not access microphone: ${msg}`);
        }
        setMicState("idle");
      });
  }, [SpeechRec]);

  const toggleMic = useCallback(() => {
    if (micState === "listening" || micState === "requesting") {
      stopMic();
    } else {
      startMic();
    }
  }, [micState, startMic, stopMic]);

  // ── Image generation ──────────────────────────────────────────────────────
  const generateImage = async (prompt: string) => {
    if (!prompt.trim()) { toast.error("Describe the image you want."); return; }
    setImgLoading(true);
    const uMsg: Msg = { role: "user", content: `🖼️ Generate image: ${prompt}`, type: "image" };
    setMessages((p) => [...p, uMsg]);
    persist(uMsg);

    try {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), 90_000);
      const resp = await fetch(`${SUPABASE_URL}/functions/v1/generate-image`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
        signal: ctrl.signal,
      });
      clearTimeout(t);
      const data = await resp.json();
      if (!resp.ok || data.error) {
        toast.error(data.error ?? "Image generation failed. Try a different prompt.");
        setMessages((p) => [...p, { role: "assistant", content: "❌ Image generation failed. Try a different prompt.", type: "text" }]);
        return;
      }
      const aMsg: Msg = { role: "assistant", content: `Here's your image: "${prompt}"`, type: "image", imageUrl: data.imageUrl };
      setMessages((p) => [...p, aMsg]);
      persist(aMsg);
      if (ttsOn) speak("Your image is ready!");
    } catch (err: any) {
      if (err?.name === "AbortError") {
        toast.error("Image generation timed out — the AI is busy. Please try again.");
        setMessages((p) => [...p, { role: "assistant", content: "⏰ Timed out. Please try again.", type: "text" }]);
      } else {
        toast.error("Network error during image generation.");
      }
    } finally {
      setImgLoading(false);
    }
  };

  // ── AI text + PDF generation ───────────────────────────────────────────────
  const sendToAI = async (history: Msg[], makePdf?: string) => {
    setLoading(true);
    const apiMsgs = history
      .filter((m) => m.type !== "image" && m.type !== "pdf-gen")
      .map((m) => ({ role: m.role, content: m.content }));

    if (makePdf) {
      const last = apiMsgs[apiMsgs.length - 1];
      if (last) last.content +=
        "\n\nWrite a thorough, well-structured response using ## headings for sections. Be detailed and comprehensive — this will be exported as a formatted document.";
    }

    try {
      const resp = await fetch(`${SUPABASE_URL}/functions/v1/chat-tutor`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: apiMsgs }),
      });

      if (!resp.ok || !resp.body) {
        const status = resp.status;
        if (status === 429) toast.error("Rate limit hit. Wait a moment.");
        else if (status === 402) toast.error("AI credits exhausted.");
        else toast.error("Something went wrong. Try again.");
        setLoading(false);
        return;
      }

      const reader = resp.body.getReader();
      const decoder = new TextDecoder();
      let buf = "", assistant = "", done = false;
      const newIdx = history.length; // index of the new assistant message
      setMessages((p) => [...p, { role: "assistant", content: "", type: makePdf ? "pdf-gen" : "text" }]);

      while (!done) {
        const { done: d, value } = await reader.read();
        if (d) break;
        buf += decoder.decode(value, { stream: true });
        let nl: number;
        while ((nl = buf.indexOf("\n")) !== -1) {
          let line = buf.slice(0, nl);
          buf = buf.slice(nl + 1);
          if (line.endsWith("\r")) line = line.slice(0, -1);
          if (!line.startsWith("data: ")) continue;
          const json = line.slice(6).trim();
          if (json === "[DONE]") { done = true; break; }
          try {
            const parsed = JSON.parse(json);
            const c = parsed.choices?.[0]?.delta?.content;
            if (c) {
              assistant += c;
              setMessages((p) => p.map((m, i) => i === p.length - 1 ? { ...m, content: assistant } : m));
            }
          } catch {
            buf = line + "\n" + buf;
            break;
          }
        }
      }

      if (assistant) {
        persist({ role: "assistant", content: assistant });

        if (makePdf) {
          // Build and store the PDF
          const doc = buildPdf(makePdf, assistant);
          const filename = `${makePdf.replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s+/g, "_").toLowerCase().slice(0, 40)}.pdf`;
          setPdfDocs((prev) => ({ ...prev, [newIdx]: doc }));
          setMessages((p) =>
            p.map((m, i) => i === p.length - 1 ? { ...m, pdfFile: filename } : m)
          );
          if (ttsOn) speak("Your PDF document is ready to download!");
        } else {
          if (ttsOn) speak(assistant);
        }
      }
    } catch {
      toast.error("Network error. Check your connection.");
    } finally {
      setLoading(false);
    }
  };

  // ── Send ──────────────────────────────────────────────────────────────────
  const send = async () => {
    const text = input.trim();
    if (!text || loading || imgLoading) return;
    setInput("");
    window.speechSynthesis?.cancel();

    if (isImageRequest(text)) {
      await generateImage(extractImagePrompt(text));
      return;
    }

    if (isPdfRequest(text)) {
      const topic = extractPdfTopic(text);
      const uMsg: Msg = { role: "user", content: text, type: "text" };
      const next = [...messages, uMsg];
      setMessages(next);
      persist(uMsg);
      await sendToAI(next, topic);
      return;
    }

    const uMsg: Msg = { role: "user", content: text, type: "text" };
    const next = [...messages, uMsg];
    setMessages(next);
    persist(uMsg);
    await sendToAI(next);
  };

  // Key handler — Enter sends
  const onKey = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); }
  };

  // ── Render ────────────────────────────────────────────────────────────────
  const isBusy = loading || imgLoading;
  const micActive = micState === "listening";
  const micPending = micState === "requesting";

  return (
    <div className="flex-1 flex flex-col overflow-hidden">

      {/* ─── Header ─────────────────────────────────────────────────── */}
      <div className="px-4 pt-12 pb-3 flex items-center gap-2.5 border-b border-border/50">
        <div className="w-7 h-7 rounded-full glass flex items-center justify-center">
          <ArrowLeft className="w-3.5 h-3.5" />
        </div>
        <div className="w-8 h-8 rounded-full bg-gradient-primary flex items-center justify-center animate-pulse-glow">
          <Sparkles className="w-3.5 h-3.5 text-white" />
        </div>
        <div className="flex-1">
          <p className="text-xs font-display font-bold">Lumina AI</p>
          <p className="text-[9px] text-accent flex items-center gap-1">
            <span className="w-1 h-1 bg-accent rounded-full" />
            Chat · Images · Voice · PDF
          </p>
        </div>

        {/* TTS toggle */}
        <button
          onClick={() => { setTtsOn((v) => !v); window.speechSynthesis?.cancel(); }}
          className={`w-7 h-7 rounded-full glass flex items-center justify-center transition-all ${ttsOn ? "text-accent" : "text-muted-foreground"}`}
          title={ttsOn ? "Mute AI" : "Speak AI responses"}
        >
          {ttsOn ? <Volume2 className="w-3 h-3" /> : <VolumeX className="w-3 h-3" />}
        </button>

        {/* Clear history */}
        {user && (
          <button onClick={clear} className="w-7 h-7 rounded-full glass flex items-center justify-center" title="Clear chat">
            <Trash2 className="w-3 h-3 text-muted-foreground" />
          </button>
        )}
      </div>

      {/* ─── Messages ───────────────────────────────────────────────── */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto scrollbar-hide px-3 py-3 space-y-2.5">
        {messages.map((m, i) => (
          <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"} animate-fade-in`}>
            <div className={
              m.role === "user"
                ? "max-w-[78%] bg-gradient-primary text-white text-[11px] px-3 py-2 rounded-2xl rounded-br-sm shadow-md whitespace-pre-wrap"
                : "max-w-[82%] glass-card text-[11px] px-3 py-2 rounded-2xl rounded-bl-sm whitespace-pre-wrap"
            }>
              {/* Generated image */}
              {m.imageUrl ? (
                <div className="space-y-1.5">
                  <p className="text-[10px] opacity-70">{m.content}</p>
                  <img src={m.imageUrl} alt="AI generated" className="rounded-xl w-full" style={{ maxHeight: 180 }} />
                  <a href={m.imageUrl} download="lumina-image.png" target="_blank" rel="noopener noreferrer"
                    className="flex items-center gap-1 text-[9px] text-accent underline">
                    <Download className="w-2.5 h-2.5" /> Download image
                  </a>
                </div>
              ) : /* PDF download button */ (m.type === "pdf-gen" && m.pdfFile) ? (
                <div className="space-y-2">
                  <p className="whitespace-pre-wrap">{m.content || <Loader2 className="w-3 h-3 animate-spin" />}</p>
                  {m.pdfFile && (
                    <button
                      onClick={() => {
                        const doc = pdfDocs[i];
                        if (doc) doc.save(m.pdfFile!);
                        else toast.error("PDF session expired — ask again please.");
                      }}
                      className="flex items-center gap-1.5 text-[10px] font-semibold px-3 py-1.5 rounded-xl text-white mt-1"
                      style={{ background: "var(--gradient-primary)" }}
                    >
                      <Download className="w-3 h-3" /> Download — {m.pdfFile}
                    </button>
                  )}
                </div>
              ) : (
                m.content || <Loader2 className="w-3 h-3 animate-spin" />
              )}
            </div>
          </div>
        ))}

        {/* Text typing indicator */}
        {loading && (
          <div className="flex justify-start animate-fade-in">
            <div className="glass-card px-3 py-2.5 rounded-2xl rounded-bl-sm flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-primary-glow animate-typing" />
              <span className="w-1.5 h-1.5 rounded-full bg-primary-glow animate-typing" style={{ animationDelay: "0.15s" }} />
              <span className="w-1.5 h-1.5 rounded-full bg-primary-glow animate-typing" style={{ animationDelay: "0.3s" }} />
            </div>
          </div>
        )}

        {/* Image generating indicator */}
        {imgLoading && (
          <div className="flex justify-start animate-fade-in">
            <div className="glass-card px-3 py-2.5 rounded-2xl rounded-bl-sm flex items-center gap-2">
              <Loader2 className="w-3 h-3 text-purple-400 animate-spin" />
              <div>
                <p className="text-[10px] text-muted-foreground">Generating image…</p>
                <p className="text-[9px] text-purple-400 flex items-center gap-1 mt-0.5">
                  <Clock className="w-2.5 h-2.5" /> {imgTimer}s · usually takes 20–60s
                </p>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* ─── Mic live transcript ─────────────────────────────────────── */}
      {(micActive || micTranscript) && (
        <div className="mx-3 mb-1 px-3 py-1.5 rounded-2xl flex items-center gap-2"
          style={{ background: "hsl(258 90% 66% / 0.15)", border: "1px solid hsl(258 90% 66% / 0.4)" }}>
          <div className="w-2 h-2 rounded-full bg-red-400 animate-pulse flex-shrink-0" />
          <p className="text-[10px] text-purple-300 flex-1 truncate">
            {micTranscript || "Listening… speak now"}
          </p>
        </div>
      )}
      {micPending && (
        <div className="mx-3 mb-1 px-3 py-1.5 rounded-2xl flex items-center gap-2 glass">
          <Loader2 className="w-3 h-3 text-accent animate-spin" />
          <p className="text-[10px] text-muted-foreground">Requesting microphone…</p>
        </div>
      )}

      {/* ─── Input bar ──────────────────────────────────────────────── */}
      <div className="px-3 pb-4 pt-2">
        <div className="glass-card rounded-full pl-3.5 pr-1.5 py-1.5 flex items-center gap-1.5">

          {/* Image mode icon */}
          <Image className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0" />

          {/* Input */}
          <input
            ref={inputRef}
            value={micActive && micTranscript ? micTranscript : input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={onKey}
            placeholder={
              micPending ? "Requesting mic…"
              : micActive ? "Listening… speak now"
              : "Ask, /image …, or 'make a PDF about…'"
            }
            readOnly={micActive}
            className="flex-1 bg-transparent outline-none text-[11px] placeholder:text-muted-foreground"
          />

          {/* Mic button */}
          <button
            onClick={toggleMic}
            disabled={micPending}
            className={`w-7 h-7 flex items-center justify-center rounded-full transition-all
              ${micActive ? "bg-red-500/20 text-red-400 ring-1 ring-red-400 animate-pulse"
                : micPending ? "text-muted-foreground opacity-50"
                : "glass text-muted-foreground hover:text-accent"}`}
            title={micActive ? "Stop listening" : "Start voice input"}
          >
            {micActive ? <MicOff className="w-3.5 h-3.5" /> : <Mic className="w-3.5 h-3.5" />}
          </button>

          {/* Send */}
          <button
            onClick={send}
            disabled={isBusy || !input.trim()}
            className="w-8 h-8 rounded-full bg-gradient-primary flex items-center justify-center text-white disabled:opacity-40 hover:scale-105 transition-transform"
          >
            {loading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Send className="w-3 h-3" />}
          </button>
        </div>

        {/* Hint pills */}
        <div className="flex justify-center gap-3 mt-1.5 flex-wrap">
          <span className="text-[9px] text-muted-foreground">💬 Chat</span>
          <span className="text-[9px] text-muted-foreground">🖼️ /image &lt;desc&gt;</span>
          <span className="text-[9px] text-muted-foreground">📝 make a pdf about…</span>
          <span className="text-[9px] text-muted-foreground">🎤 Tap mic to speak</span>
        </div>
      </div>
    </div>
  );
};
